version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: metube_metube_1
      APP_PORT: 8081

  metube:
    image: ghcr.io/alexta69/metube:2024-09-22@sha256:95b2dbe3fcf6fdb88744a928078342c573900965556dd5ab559facb2a9b3b168
    restart: on-failure
    volumes:
      - ${UMBREL_ROOT}/data/storage/downloads/metube:/downloads